services:
  redis:
    image: redis:7.0.2-alpine
    restart: always
    container_name: sport_manager_redis
    volumes:
      - redis_data:/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"
    expose:
      - "6379"

  db:
    image: postgres:16-alpine
    restart: always
    container_name: sport_db_postgres
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 3

  mongodb:
    image: mongo:6.0.1-alpine
    container_name: sport_manager_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand(\"ping\").ok' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  sport_web_api:
    image: sport_manager_api:latest
    build:
      context: .
      args:
        - DEV=true
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy

volumes:
  data:
  redis_data:
  mongo_data:
