services:
  redis:
    image: redis:7.0.2-alpine
    restart: always
    container_name: sport_manager_redis
    volumes:
      - redis_data:/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"
    expose:
      - "6379"
  sport_db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 3
  sport_web_api:
    image: sport_manager_api:latest
    build:
      context: .
      args:
        - DEV=true
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      sport_db:
        condition:
          service_healthy
      redis:
        condition:
          service_healthy
volumes:
  data:
  redis_data: